name: Deploy Production
on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: DigitalOcean App Platform deployment
      uses: digitalocean/app_action@main
      with:
        app_name: dc-children-church-checkin-prod
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
