name: Yarn Build Check
on:
  pull_request:
    # Sequence of patterns matched against refs/heads
    branches:    
      - main

jobs:
  build:
    env:
        NEXT_PUBLIC_GRAPHQL_ENDPOINT: https://digi-church-be-app-qjrjc.ondigitalocean.app/graphql
    name: Test Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install # will run `yarn install` command
      - name: Build production bundle
        uses: borales/actions-yarn@v4
        with:
          cmd: build
